import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const customMonadi = localFont({
  src: [
    {
      path: "./fonts/ArbFONTS-Monadi.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-monadi",
});

export const metadata: Metadata = {
  title: "الصدفية و الاكزيما",
  description: "Generated by MTN-Development",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${customMonadi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
